version: '3.9'
services:
  postgres:
    image: postgres:16
    env_file:
     - ./notes/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
   build:
     context: .
   env_file:
     - ./notes/.env
   container_name: django_app
   command: ["/django_app/docker/app.sh"]
   ports:
     - 8000:8000
   depends_on:
     - postgres


