# Generated by Django 5.0 on 2023-12-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_note_user_tag_user_alter_tag_name_and_more'),
        ('noteapp', '0005_remove_note_authors_note_author_and_more'),
    ]

    operations = [
    ]
