# Generated by Django 4.2.7 on 2023-12-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0004_alter_note_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='authors',
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='noteapp.author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='born_date',
            field=models.CharField(max_length=250),
        ),
    ]
